
#          MMP"""""""MM                  dP            dP
#          M' .mmmm  MM                  88            88
# 88d888b. M         `M 88d8b.d8b. .d888b88 .d8888b. d8888P .d8888b.
# 88'  `88 M  MMMMM  MM 88'`88'`88 88'  `88 88'  `88   88   Y8ooooo.
# 88       M  MMMMM  MM 88  88  88 88.  .88 88.  .88   88         88
# dP       M  MMMMM  MM dP  dP  dP `88888P8 `88888P'   dP   `88888P'
#          MMMMMMMMMMMM



# ┌──────────────────┐
# │Config directories│
# └──────────────────┘

source = /home/ram/.config/hypr/UserConfigs/StartupApps.conf
source = /home/ram/.config/hypr/UserConfigs/WindowRules.conf
source = /home/ram/.config/hypr/UserConfigs/UserKeybinds.conf
source = /home/ram/.config/hypr/UserConfigs/UserAnimations.conf
source = /home/ram/.config/hypr/UserConfigs/UserCustomization.conf
source = /home/ram/.config/hypr/UserConfigs/UserLayout.conf
source = /home/ram/.config/hypr/UserConfigs/UserPerms.conf

# ┌────────────────┐
# │Config structure│
# └────────────────┘

# ~/.config/hypr/
# ├── hyprland.conf                      | You are here!
# |
# ├──── UserConfigs/                     | User customization layer
# │   ├── StartupApps.conf
# │   ├── UserKeybinds.conf
# │   ├── UserAnimations.conf
# │   ├── UserCustomization.conf
# │   ├── UserLayout.conf
# │   ├── UserPerms.conf
# |
# ├──── UserScripts/                     | Utilities
# │   ├── accel.py                             Mouse bezier curve calculator
# │   ├── launch.sh                            Waybar refresh
#

# ┌────────────┐
# │Font credits│
# └────────────┘

# Site credits:
# https://www.asciiart.eu/text-to-ascii-art

# Headings:
#
# Font: Nancyj-Fancy

# Subheadings:
#
# Font: Term | Frame: Box drawings light


monitor=eDP-1,1920x1200@60.00,960x800,1.25
