
# MMP"""""""MM            dP            MP""""""`MM   dP                       dP
# M' .mmmm  MM            88            M  mmmmm..M   88                       88
# M         `M dP    dP d8888P .d8888b. M.      `YM d8888P .d8888b. 88d888b. d8888P
# M  MMMMM  MM 88    88   88   88'  `88 MMMMMMM.  M   88   88'  `88 88'  `88   88
# M  MMMMM  MM 88.  .88   88   88.  .88 M. .MMM'  M   88   88.  .88 88         88
# M  MMMMM  MM `88888P'   dP   `88888P' Mb.     .dM   dP   `88888P8 dP         dP
# MMMMMMMMMMMM                          MMMMMMMMMMM



# Autostart necessary processes (like notifications daemons, status bars, etc.)

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = swww-daemon
