
# M""MMM""MMM""M oo                dP                     MM"""""""`MM          dP
# M  MMM  MMM  M                   88                     MM  mmmm,  M          88
# M  MMP  MMP  M dP 88d888b. .d888b88 .d8888b. dP  dP  dP M'        .M dP    dP 88 .d8888b. .d8888b.
# M  MM'  MM' .M 88 88'  `88 88'  `88 88'  `88 88  88  88 MM  MMMb. "M 88    88 88 88ooood8 Y8ooooo.
# M  `' . '' .MM 88 88    88 88.  .88 88.  .88 88.88b.88' MM  MMMMM  M 88.  .88 88 88.  ...       88
# M    .d  .dMMM dP dP    dP `88888P8 `88888P' 8888P Y8P  MM  MMMMM  M `88888P' dP `88888P' `88888P'
# MMMMMMMMMMMMMM                                          MMMMMMMMMMMM



# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules=

# ┌───────────────┐
# │TUI Windowrules│
# └───────────────┘

# Adjustable rule for terminal apps:

# windowrule {
#    name = kitty-rules
#    match:class = kitty
#
#    float = on
#    size = 764 440
#    center = true
#}

windowrule {
    name = kitty-rules
    match:class = kitty

    float = on
    size = 764 440
    center = true
}

windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }
